### ISSUE TITLE
[Bug] Desolator not working properly with Ancient Scepter

### ISSUE THREAD

**Issue by Morpok** [TheTimeSweeper/the#23]
When you active the upgraded "Spread the Doom" Skill with Ancient Scepter, it works once then it's swapped back to the original skill for the duration of the stage. It's switched back when you start a new stage, but breaks again when you use it.

![Example](https://github.com/TheTimeSweeper/the/assets/167143000/b7c89ee4-2ffa-43cb-a35c-d1c98eecc8b7)

**Comment by TheTimeSweeper** [comment]
Please give a log and/or send r2modman profile code so I can look into this

**Comment by Morpok** [comment]
018ef362-46fc-cdf7-7994-e46b66bd3812

**Comment by TheTimeSweeper** [comment]
tracked the issue down to zetaspects. will push a fix when I figure this out but I have no idea what's going on other than it only happens when zetaspects is installed as well.

**Comment by Gudmundyr** [comment]
I Don't know if this will help, I also experience the same bug as Morpok with Ancient Scepter on Desolator, but I do not use ZetAspects. Additionally, "Spread of Doom" upgraded by Ancient Scepter goes on cooldown when I use the ability "Reactor" or equipment. The cooldown timer for the upgraded "Spread of Doom" resets with either "Reactor" or an equipment being used. This stops happening once I use the upgraded "Spread of Doom" (since afterwards, it reverts to normal).

Baseline
![Nothing Yet](https://github.com/TheTimeSweeper/the/assets/170901328/3659ee36-3eae-4bb5-8690-bc8526d4d43e)
Reactor puts ult on cooldown
![Reactor CD](https://github.com/TheTimeSweeper/the/assets/170901328/9ae34307-6f69-45a2-a8b6-aef9affb4244)
Equipment resets ult cooldown timer
![Equip Reset Ult CD Time](https://github.com/TheTimeSweeper/the/assets/170901328/91a34995-a281-4c82-a38e-c91907a560df)

Heres the profile code: 018fb79e-8e3d-8e81-9efa-72bc4bbceb2f

**Comment by TheTimeSweeper** [comment]
killed this in the ass once and for all. my fault for trying to do things right :P
